services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tgDB
      POSTGRES_USER: tgBot
      POSTGRES_PASSWORD: tgBotic
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bot:
    build: .
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
