version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tg_bot_db
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: tg_pass
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
